export const BUY_CAKE = "BUY_CAKE";
export const RESTOCK_CAKES = "RESTOCK_CAKES";
export const UPDATE_BUY_INPUT = "UPDATE_BUY_INPUT";
export const SET_ERROR = "SET_ERROR";
export const UPDATE_RESTOCK_INPUT = "UPDATE_RESTOCK_INPUT";
